### PR TITLE
Added PIDs for T-Display-S3

### PR DESCRIPTION
**Pull request by netroy**
More info on the board can be found here
* https://github.com/Xinyuan-LilyGO/T-Display-S3
* https://www.lilygo.cc/products/t-display-s3?variant=42284559827125

### CODE REVIEW

**Comment by Spritetm** [comment]
I'm OK with merging this, but can you please rebase on the pull request I merged just now?

**Comment by netroy** [comment]
@Spritetm done

**Comment by Spritetm** [comment]
Looks good, merged, thanks!

**Comment by netroy** [comment]
@rcarteraz you need to open a separate pull request.

**Comment by Spritetm** [comment]
@rcarteraz Fyi, that's kind-of a gray area in the rules as defined right now. I discussed it internally, but unfortunately we don't really want to give out PIDs unless they're actually used in the USB hardware in the ESP chip itself.

**Comment by Spritetm** [comment]
@rcarteraz No sorry. See the changes I pushed to the README in the repo: we want the PID to be used in the USB interface in the ESP. Since the C3 does not have an USB interface with a configurable PID, it doesn't qualify per definition.

**Pull request merged**
