### PR TITLE
Add YD-ESP32-S3

### PR DESCRIPTION
**Pull request by bill88t**
I got this board off of ebay.

Some stuff of it is detailed here:
https://github.com/vcc-gnd/YD-ESP32-S3

I have no affiliation with the board maker.
I just got the board and want to make an official CircuitPython port.
I have already finished the technical side of the port.

### CODE REVIEW

**Comment by bill88t** [comment]
Rolled over the pids accounting for #89.
Should further changes be needed, just let me know.

**Comment by Spritetm** [comment]
Can you rebase on the current master? After that, I'll merge.

**Comment by bill88t** [comment]
Github wasn't cooperating much, sorry for this. It's ready now.

**Comment by Spritetm** [comment]
No problem, looks all good now, I'll merge.

**Pull request merged**
