### PR TITLE
Add PID for Cytron Maker Feather AIoT S3

### PR DESCRIPTION
**Pull request by waiweng83**
Hi, I would like to request to add the PID for Cytron Maker Feather AIoT S3.

A short description of what the device is going to do (e.g. cat tracker with USB trace download)
> **A development board for ESP32-S3 in Adafruit Feather form factor.**

What chip are you using for the device the PID is allocated for (e.g. ESP32-S2)
> **ESP32-S3**

If you're requesting a PID on behalf of a company, please mention the name of the company
> **Cytron Technologies**

If applicable/available, a website or other URL with information about your product or company
> www.cytron.io

### CODE REVIEW

**Comment by Spritetm** [comment]
Looks good. I just merged a previous PR, can you rebase? After that's done, I'll merge.

**Comment by waiweng83** [comment]
Done.

**Comment by Spritetm** [comment]
Excellent, thanks!

**Comment by waiweng83** [comment]
Thanks :)

**Pull request merged**
