### PR TITLE
Update to allocated PID for 4 devices for Talk All Sport

### PR DESCRIPTION
**Pull request by TalkAllSport-JW**
These devices make up the four parts of a sports scoring system. 
They are using ESP32-S3-WROOM-1 modules.
The devices will be a commercial product so require to have a professional driver installed, thus prefer to not use. TinyUSB as the PID. The Company is Talk All Sport, see talkallsport.com.

Thanks in advance

### CODE REVIEW

**Comment by Spritetm** [comment]
Looks good, but can you change the formatting to fall in line with the rest? Specificaly, put a space between the PID and the | char please.

**Comment by Wind-stormger** [comment]
#96 , 0x8171 to 0x8174 have been requested.

Your pull request may conflict with his.

**Comment by Spritetm** [comment]
Fixed up & merged, thanks!

**Comment by TalkAllSport-JW** [comment]
Thank you

**Pull request merged**
