### PR TITLE
Update allocated PID

### PR DESCRIPTION
**Pull request by raviypujar**
Device Purpose:
VALTRACK-V4-VTS-ESP32-C3 is a 4G-LTE Vehicle tracking device  VALTRACK-V4-MFW-ESP32-C3 is a 4G-LTE Asset tracking device 

Chips used:

ESP32-C3
EPS32-C3FH4

Reason for PID req:
Device requires custom drivers for parameter configuration of cellular connection parameters & server details.

### CODE REVIEW

**Comment by Spritetm** [comment]
Looks good, but we'd like a few more bits of info:
- What's the name of your company (if any)?
- Do you have a website or something for the product?

**Comment by raviypujar** [comment]
> Looks good, but we'd like a few more bits of info:
> 
> * What's the name of your company (if any)?
Valetron Systems Private Limited, India
> * Do you have a website or something for the product?
Please check here, 
https://www.valetron.com/store/valtrack-v4-vts-esp-32-c3-4g-lte-gps-tracker.html
https://docs.valetron.com/wiki/products/valtrack-v4-vts-esp32-c3

**Comment by igrr** [comment]
> ESP32-C3

That chip doesn't have a programmable PID, does it?

**Comment by raviypujar** [comment]
> > ESP32-C3
> 
> That chip doesn't have a programmable PID, does it?

It says vendor can modify PID in below link, Please confirm.
https://docs.espressif.com/projects/esp-matter/en/main/esp32c3/production.html

**Comment by Spritetm** [comment]
The link refers to Matter PID/VIDs, not USB PID/VIDs. The C3 indeed does not have a programmable PID and VID.

**Comment by raviypujar** [comment]
Thank you. What's the solution for this? Use other device VID & PID?

**Comment by Spritetm** [comment]
If you indeed need a custom PID/VID, you can use an ESP32S2 or S3 or other chip that has an USB-OTG peripheral in it.

**Comment by raviypujar** [comment]
Understood & Thank you very much for the quick response. Closing this.

**Pull request closed without merging**
