### PR TITLE
Add PIDs for Waveshare ESP32-S3-Zero

### PR DESCRIPTION
**Pull request by Y1hsiaochunnn**
Adding PID for Waveshare ESP32-S3-Zero board to be added to CircuitPython, arduino-esp32 and PlatformIO.

Product wiki: [ESP32-S3-Zero](https://www.waveshare.com/wiki/ESP32-S3-Zero)

### CODE REVIEW

**Comment by Y1hsiaochunnn** [comment]
Hi @Spritetm ,
plz mention me if needs to change the PID allocation

**Comment by Spritetm** [comment]
@Y1hsiaochunnn Yes, please do. You're next in line, so as soon as you do that, I'll merge.

**Comment by Y1hsiaochunnn** [comment]
@Spritetm how about now?

**Comment by Spritetm** [comment]
Looks good, merged.

**Pull request merged**
