### PR TITLE
CircuitArt FeatherS3 development custom board

### PR DESCRIPTION
**Pull request by CircuitART**
added 3 PIDS for new ESP32S3 custom board

### CODE REVIEW

**Comment by Spritetm** [comment]
I forgot to ask last time, but can you please follow the steps under 'How do I get a PID in this range?' in the readme.md of this repo? Also, please give your MR a better name.

**Comment by CircuitART** [comment]
sure checking now

**Comment by CircuitART** [comment]
Hi Here is the required info and sorry about missing it the first time, Hopefully you will find it in order.

This development board is a part of learning envoirment for young kids to learn Circuitpythin (including the previous PR's board Hexky_S2)
The Chip is ESP32S3
The PIDS are needed for Tinyuf2 bootloader and Circuitpython uf2
I am requesting the PIDs on behalf of my company (FutureKeys)
https://futurekeys.net/index.html

Thank you

**Comment by Spritetm** [comment]
Excellent, thanks for changing/amending the info. Merged!

**Comment by CircuitART** [comment]
appreciate ur support, Thank you :)

**Comment by UnexpectedMaker** [comment]
@CircuitART can I recommend you change you product name? I'm already using FeatherS3 and a product name and brand. Calling your boards FeatherS3 is just going to confuse people.

**Pull request merged**
