### PR TITLE
 PHITEK

### PR DESCRIPTION
**Pull request by phitek-dev**
I would like to reserve a USB PID for a product I am developing.

### CODE REVIEW

**Comment by Spritetm** [comment]
Can you also tell us the things we require in the README of this repo? Copy-paste:

- A short description of what the device is going to do (e.g. cat tracker with USB trace download)

- What chip are you using for the device the PID is allocated for (e.g. ESP32-S2)

- Why you need a custom PID (and can't, for instance, use the default TinyUSB PIDs)

- If you're requesting a PID on behalf of a company, please mention the name of the company

- If applicable/available, a website or other URL with information about your product or company

**Comment by Spritetm** [comment]
Note that in the mean time a separate request has been merged; you probably want to rebase and grab the next available PID.

**Comment by phitek-dev** [comment]
Hi Jeroen:My plan is to use the ESP32-C3 family, so I will cancel my PR.Thank You for your support.RegardsPhil SikoraSent from my Galaxy
-------- Original message --------From: Jeroen Domburg ***@***.***> Date: 11/10/21  9:03 PM  (GMT-05:00) To: espressif/usb-pids ***@***.***> Cc: phitek-dev ***@***.***>, Author ***@***.***> Subject: Re: [espressif/usb-pids]  PHITEK (PR #27) 
Note that in the mean time a separate request has been merged; you probably want to rebase and grab the next available PID.

**Comment by Spritetm** [comment]
Cool, I'll close this request then. Good luck with the project!

**Pull request closed without merging**
