### PR TITLE
Update allocated-pids.txt

### PR DESCRIPTION
**Pull request by ESP32DE**
Hi

thank you for offer the option of using a PID allocated under the Espressif VID.
Here is my Request list :)

0x8001 | ESP32DE ESP32-S2-Stickley-MIDI-PRO
audio pro usb-device with expanded customized AUDIO/MIDI functions
ESP32-S2 is used
use a custom USB class on my ESP32 which needs a non-standard driver on the host
https://github.com/ESP32DE

0x8002 | ESP32DE ESP32-C3-Stickley-MIDI-PRO
audio pro usb-device with expanded customized AUDIO/MIDI functions
ESP32-C3 is used
use a custom USB class on my ESP32 which needs a non-standard driver on the host
https://github.com/ESP32DE

0x8003 | ESP32DE ESP32-S3-Stickley-MIDI-PRO
audio pro usb-device with expanded customized AUDIO/MIDI functions
ESP32-S3 is used
use a custom USB class on my ESP32 which needs a non-standard driver on the host
https://github.com/ESP32DE

0x8004 | ESP32DE WiFi-CAN-Bridge-PRO
WIFI - TWAI/CAN pro usb-device with customized functions
ESP32-S2, ESP32-C3, ESP32-S3 is used 
use a custom USB class on my ESP32 which needs a non-standard driver on the host
https://github.com/ESP32DE

0x8005 | ESP32DE WiFi-OTG-Bridge-PRO
WIFI - OTG pro usb-device with customized functions
ESP32-S2, ESP32-C3, ESP32-S3 is used 
use a custom USB class on my ESP32 which needs a non-standard driver on the host
https://github.com/ESP32DE

0x8006 | ESP32DE WiFi-MCU-Bridge-PRO
WIFI - MCU pro usb-device with customized functions for communication between PC and MCU
ESP32-S2, ESP32-C3, ESP32-S3 is used 
use a custom USB class on my ESP32 which needs a non-standard driver on the host
https://github.com/ESP32DE

0x8007 | ESP32DE LIVE-STYLER-PRO 
WIFI - pro usb-device with customized functions for communication between PC and LIVE-STYLER PRO TCP Versions 
ESP32-S2, ESP32-C3, ESP32-S3 is used 
use a custom USB class on my ESP32 which needs a non-standard driver on the host
https://github.com/ESP32DE

0x8008 | ESP32DE STICKLEY-PRO
WIFI - pro usb-device with customized functions for communication between PC and ESP32-xx-Stickley-MIDI-PRO 
ESP32-S2, ESP32-C3, ESP32-S3 is used 
use a custom USB class on my ESP32 which needs a non-standard driver on the host
https://github.com/ESP32DE

0x8009 | ESP32DE MCU-Commander
WIFI - MCU pro usb-device with customized functions for communication between PC and MCU
ESP32-S2, ESP32-C3, ESP32-S3 is used 
use a custom USB class on my ESP32 which needs a non-standard driver on the host
https://github.com/ESP32DE

0x800A | ESP32DE RESERVE -A- (TESTDRIVE)
DONGLE usb-device with customized functions for communication between PC and connected MCU Device 
ESP32-S2, ESP32-C3, ESP32-S3 is used 
use a custom USB class on my ESP32 which needs a non-standard driver on the host
https://github.com/ESP32DE

0x800B | ESP32DE RESERVE -B- (TESTHOST)
DONGLE usb-device with customized functions for communication between PC and connected MCU Device 
ESP32-S2, ESP32-C3, ESP32-S3 is used 
use a custom USB class on my ESP32 which needs a non-standard driver on the host
https://github.com/ESP32DE

0x800C | ESP32DE RESERVE -C- (TESTDEVICE)
DONGLE usb-device with customized functions for communication between PC and connected MCU Device 
ESP32-S2, ESP32-C3, ESP32-S3 is used 
use a custom USB class on my ESP32 which needs a non-standard driver on the host
https://github.com/ESP32DE

0x800D | ESP32DE RESERVE -D- (TEST NEURONAL BASE STATION)
DONGLE usb-device with customized functions for communication between PC and connected MCU Device 
ESP32-S2, ESP32-C3, ESP32-S3 is used 
use a custom USB class on my ESP32 which needs a non-standard driver on the host
https://github.com/ESP32DE

0x800E | ESP32DE RESERVE -E- (TEST REMOTE)
DONGLE usb-device with customized functions for communication between PC and connected MCU Device 
ESP32-S2, ESP32-C3, ESP32-S3 is used 
use a custom USB class on my ESP32 which needs a non-standard driver on the host
https://github.com/ESP32DE

0x800F | ESP32DE RESERVE -F- ( OSZ ) 
DONGLE usb-device with customized functions for communication between PC and connected MCU Device 
ESP32-S2, ESP32-C3, ESP32-S3 is used 
use a custom USB class on my ESP32 which needs a non-standard driver on the host
https://github.com/ESP32DE

0x8010 | ESP32DE PSRAMBANK-PRO
WIFI - PSRAMBANK pro usb-device with customized functions for communication between PC and MCU
ESP32-S2, ESP32-C3, ESP32-S3 is used 
use a custom USB class on my ESP32 which needs a non-standard driver on the host
https://github.com/ESP32DE

0x8011 | ESP32DE WiFi-DONGLE
WIFI - DONGLE usb-device with customized functions for communication between HOST and Device
ESP32-S2, ESP32-C3, ESP32-S3 is used 
use a custom USB class on my ESP32 which needs a non-standard driver on the host
https://github.com/ESP32DE

0x8012 | ESP32DE Bluetooth-DONGLE
Bluetooth - DONGLE usb-device with customized functions for communication between HOST and Device
ESP32-S2, ESP32-C3, ESP32-S3 is used 
use a custom USB class on my ESP32 which needs a non-standard driver on the host
https://github.com/ESP32DE

0x8013 | ESP32DE WiFi-BT-BLE-DONGLE
WIFI-BT-BLE DONGLE usb-device with customized functions for communication between HOST and Device
ESP32-S2, ESP32-C3, ESP32-S3 is used 
use a custom USB class on my ESP32 which needs a non-standard driver on the host
https://github.com/ESP32DE

0x8014 | ESP32DE AiIoT-DONGLE
WIFI - DONGLE usb-device with customized functions for communication between HOST and AiIoT DEVICE
ESP32-S2, ESP32-C3, ESP32-S3 is used 
use a custom USB class on my ESP32 which needs a non-standard driver on the host
https://github.com/ESP32DE

0x8015 | ESP32DE IoT-DONGLE
WIFI - DONGLE usb-device with customized functions for communication between HOST and IoT Device
ESP32-S2, ESP32-C3, ESP32-S3 is used 
use a custom USB class on my ESP32 which needs a non-standard driver on the host
https://github.com/ESP32DE

0x8016 | ESP32DE WEBUSB-PRO
DONGLE usb-device with customized functions for wireless communication between HOST and customized IoT Devices
ESP32-S2, ESP32-C3, ESP32-S3 is used 
use a custom USB class on my ESP32 which needs a non-standard driver on the host
https://github.com/ESP32DE

0x8017 | ESP32DE TINY-SHinY
DONGLE usb-device with customized functions for communication between HOST and SHiny-Device's - a MESH Build of eMbedded IoT's in the Home
ESP32-S2, ESP32-C3, ESP32-S3 is used 
use a custom USB class on my ESP32 which needs a non-standard driver on the host
https://github.com/ESP32DE

0x8018 | ESP32DE devflowcharter PRO
DONGLE usb-device with customized functions for communication between HOST and connected MCU Device on devflowcharter
ESP32-S2, ESP32-C3, ESP32-S3 is used 
use a custom USB class on my ESP32 which needs a non-standard driver on the host
https://github.com/ESP32DE

0x8019 | ESP32DE SOFTUSB PRO
DONGLE soft-usb-device with customized functions for communication between PC and connected MCU Device
ESP32, ESP32-PICO-D4, ESP32-PICO-V3, ESP32-PICO-V3-02 is used 
use a custom SOFT USB class on my ESP32 which needs a non-standard driver on the host
https://github.com/ESP32DE

best wishes
rudi ;-)

### CODE REVIEW

**Comment by Spritetm** [comment]
Hi Rudi,

Apologise for answering this late, somehow Github refuses to send me emails for notifications on this repo. First of all, the C3 does not have a dedicated USB port with configurable PID/VID, so there is no need/use to request PIDs for products that have this chip in them. Secondly, please don't pre-reserve PIDs, request them as they are needed. Thirdly, can you expand a bit more on why your devices all need a custom USB class? This is both to make sure people don't randomly request a whole bunch of USB PIDs as well as see if we are missing functionality from our existing USB stack.

**Comment by ESP32DE** [comment]
> 
> 
> Hi Rudi,
> 
> Apologise for answering this late, somehow Github refuses to send me emails for notifications on this repo. First of all, the C3 does not have a dedicated USB port with configurable PID/VID, so there is no need/use to request PIDs for products that have this chip in them. Secondly, please don't pre-reserve PIDs, request them as they are needed. Thirdly, can you expand a bit more on why your devices all need a custom USB class? This is both to make sure people don't randomly request a whole bunch of USB PIDs as well as see if we are missing functionality from our existing USB stack.


Well Jeroen, 

You offer this, i request. 
That C3 does not have a dedicated USB port with configurable PIC/VID is new to me.
I have other Information. Also i want use the C3 the same way i do it with S2 now and S3 later.
I want be sure, that i get the PID'S for using them in my PCB Desings for my Products, my Promotion and Notice.
I did it at first, also i want only this PIDS i did request. It is no random - they are real. 

I see @UnexpectedMaker request now the PID's after i did  

image

Does you not say, "for easy managing purposes we'd like to keep the customer allocated PIDs sequential."
Why them this guy request MY requested PID'S which i did ?
Will it be a new power struggle between important and unimportant?
Or does your post mean, you want not that my request does get my requested PIDS form start 0x8001
or does it mean, i should never request again ?

Jeroen, close it or or grant it. I will not justify myself for my projects and what I will do.

rudi

**Comment by ESP32DE** [comment]
@Spritetm 
ESP32S2Stickley is a Product Serie with expanded MIDI and more ! No Random Dandom-

https://twitter.com/eMbeddedHome/status/1350585483085152259

I want not "twitter" more details for each PID and the Product IDEA behind for several reason.

Like i say - grant or close my reqeuest'S
it take much time to list all and request all - i do not edit or willing to sort out.
it is for the PID - i will use the PID basicly for the S2 - if i request for S2, C3, S3 ...
and C3 need not a PID - then register the PID for S2 only , if you not want that we request also the PID for an other MCU ( S3 ) and you want a new request with a new PID request,. I request the PID for the PRODUCT like PID stands for it.


0x8001 is the first request for ESP32-S2-Stickley ...



all my requested PIDS have a description, a why and for what like you wanted in the readme

PID : 0x8001 | ESP32DE ESP32-S2-Stickley-MIDI-PRO
DESC: audio pro usb-device with expanded customized AUDIO/MIDI functions
CHIP: ESP32-S2 is used
WHY: use a custom USB class on my ESP32 which needs a non-standard driver on the host

i do not repeat again.

**Comment by Spritetm** [comment]
PIDs will be allocated sequentially dependent on whose pull request gets approved first. If we do not do it this way, someone might retract their pull request and we're left with holes in the allocation; something we specifically do not want. We specifically do not want people to ask for a PID when they can use one of the classes we have pre-allocated for the standard classes - hence us requesting more info than a copy-pasted line of 'needs custom driver', especially given the fact you're requesting a great deal of PIDs at the same time. 

The rules here as stated are that A. you keep the PID list sequential and B. you explain why you cannot use one of the default classes. Given the fact that you state you are unwilling to do these, I will grant your request and close this PR.

**Comment by Spritetm** [comment]
(Also, note that your image shows exactly what we're trying to stop from happening - you use a standard USB class, and as such you can use the reserved PID for that class and do not need a separate driver or PID.)

**Comment by ESP32DE** [comment]
> 
> 
> (Also, note that your image shows exactly what we're trying to stop from happening - you use a standard USB class, and as such you can use the reserved PID for that class and do not need a separate driver or PID.)

NO - IT is not a standard MIDI - 
cause it works with the PID ! Not with the Standard MIDI CLASS
I wrote my OWN MIDI CLASS with EXPANDED Function and they are not STANDARD in the MIDI CLASS

The Live-Styler is also a Product which i work on FYI

You merged my requested PID now to an other Request.
I will check out his PROBLEM with this and YOU on other place Jeroen
We will see what the result will be then.

I know now how you tick too Jeroen.
I will clear this problems with you and the future with us and 
why we should work with ESPRESSIF stúffs further more.

I will mess this with your act here for now.
You did wrong to me!

**Comment by ESP32DE** [comment]
Please move the postings talks in the document folder at esp32.com to an other place...
https://esp32.com/viewtopic.php?f=5&t=18967
cause we have a general talk forum for this.

it is not the quality of espressif that this forum goes more the more mesie character like bbs.espressif.com ( ESP8266 ) is now.

Why you break the rules which you speak about them ?
the document forum is for documents only not?
also we have a document request forum, 
https://esp32.com/viewtopic.php?f=5&t=905
which are the postings made who need documents
the document forum should be only for the documents not?

perhabs you want move the ISA thread 
https://esp32.com/viewtopic.php?f=5&t=17549
to the request document thread?

perhabs this post in the document folder to the showcase?
https://esp32.com/viewtopic.php?f=5&t=18754

you neglect your (forum) work i think Jeroen.

i waste time with you and your logic on rules.
i did all what you wrote in the readme, but you closed my request for your choice i gave ( grant or close )

**Comment by ESP32DE** [comment]
@Spritetm 

for the protocol

image


"The rules here as stated are that 
A. you keep the PID list sequential and 
B. you explain why you cannot use one of the default classes. 

Given the fact that you state you are unwilling to do these, 
I will grant your request and close this PR."


Read my post undrunken Jeroen!

Your RULE A is it sequential? YES 0x08001 follows after 0x8000 not?
0x8001 | ESP32DE ESP32-S2-Stickley-MIDI-PRO

Description like in the readme wanted:
audio pro usb-device with expanded customized AUDIO/MIDI functions

Which chip like in the readme:
ESP32-S2 is used

Your RULE B why you cannot use one of the default classes:
Why: use a custom USB class on my ESP32 which needs a non-standard driver on the host

Link or anything:
https://github.com/ESP32DE

I waste time with you Jeroen like it was allways
perhabs you want work at the forum more?

**Comment by ESP32DE** [comment]
@Spritetm 

until it is not clear whit you for whom you work jeroen ( Espressif or UM or Schtoeta ingenieering limited or own..  ) 
we stop all work with espressif products for now to clear this directly.

FYI: ( no randomly dandom things ) 
The Serie [Stickley2021](https://github.com/ESP32DE/Stickley2021) we paused for now.
Waste time again with you and your "HOT TIP" to go more with ESP32-C3 and not with ESP32-S3 
in this. 

No we are not more any friends Jeroen. 
Now i know how you tick and so we are more the more Counterparties / Competitors.
So i am glad to know this before we go on to talk about our plans and future visions and details.
I  can buy at DigiKey or Mouser Espressif Stuff is there any need to use it in the future.
You're more likely to be from the other party, why i should then talk with you over this.

**Pull request closed without merging**
