### PR TITLE
Added a Smart Bee Design Board

### PR DESCRIPTION
**Pull request by strid3r21**
the "Bee Data Logger" is a soon to be released Esp32-s3 data logger board. requesting on behalf of my company Smart Bee Designs LLC why i need this - for device identification

### CODE REVIEW

**Comment by Spritetm** [comment]
Sure, but note someone snuck in a request just before yours - if you can rework your request to apply cleanly on the current master, I'll merge.

**Comment by strid3r21** [comment]
> Sure, but note someone snuck in a request just before yours - if you can rework your request to apply cleanly on the current master, I'll merge.

should be fixed now.

**Comment by Spritetm** [comment]
Technically, you also had to rebase it, but I fixed that for you. Merged!

**Comment by strid3r21** [comment]
> Technically, you also had to rebase it, but I fixed that for you. Merged!

thanks!

**Pull request merged**
