### PR TITLE
ADD model ESP32-S3-Touch-LCD-1.85 ...

### PR DESCRIPTION
**Pull request by Sail-211010**
Several chip models have been added for easy customer operatio

corresponding product:（Information on the details page）
https://www.waveshare.net/search.html?kw=ESP32

### CODE REVIEW

**Comment by Spritetm** [comment]
Do these boards actually have Arduino/CircuitPython/UF2 support?

**Comment by Sail-211010** [comment]
Hardware is supported, software will gradually support these things, yes

**Comment by Spritetm** [comment]
I will merge this for now. However, as I told your colleague in their PR: We're not really happy with a company requesting loads of PIDs, especially for unreleased boards. You may want to communicate to your manager or whoever is responsible for it that if they want to build loads of variations of boards that use USB, they probably will be better off buying their own USB VID.

**Comment by Sail-211010** [comment]
OK，I will report the situation to my supervisor

**Comment by Spritetm** [comment]
Also, I didn't spot that you had models with the ESP32-C6 in there. Those chips do not have an USB-OTG device and cannot have a PID assigned. I'll remove those from the allocated PID list.

**Comment by Sail-211010** [comment]
OK  ,See what you mean

**Pull request merged**
