### PR TITLE
Add PID for cezerio dev ESP32C6

### PR DESCRIPTION
**Pull request by DogushC**
cezerio dev ESP32C6 is an development board based on Espressif ESP32-C6. 
Visit [webpage](https://cezerio.com/cezerio_dev_esp32c6) for detailed infos.
PID is neccesery for Arduino and Python.

### CODE REVIEW

**Comment by Spritetm** [comment]
Sorry, but no. The ESP32C6 does not have an USB-OTG peripheral, and the PID for the USB-serial-JTAG device cannot be changed, so if I were to merge this, you would not have a method of using the PID allocated.

**Comment by DogushC** [comment]
I see. But [Waveshare ESP32-C6-Zero](https://www.waveshare.com/wiki/ESP32-C6-Zero) and [Waveshare ESP32-C6-Pico](https://www.waveshare.com/wiki/ESP32-C6-Pico) were merged a few days ago.

**Comment by Spritetm** [comment]
You are correct, those should never have been allocated PIDs. I'll remove them.

**Comment by DogushC** [comment]
Last thing. ESP32-C3 series have not USB-OTG peripheral too. Lolin C3 Mini and uPesy ESP32C3 boards have allocated PIDs.

**Pull request closed without merging**
